import { test, expect, type Page, type Route } from '@playwright/test'

const API_BASE = (process.env.VITE_API_BASE_URL || 'http://127.0.0.1:3002').replace(/\/$/, '')

type MeetingSessionSummary = {
  session_id: string
  title: string
  participants: string[]
  entry_count: number
  created_at: string
  updated_at: string
}

type MeetingSessionDetail = MeetingSessionSummary & {
  language_hint?: string
  tags?: string[]
  summary?: string | null
  entries: Array<{
    text: string
    speaker: string
    created_at: string
    metadata?: Record<string, string>
  }>
}

const fulfillJson = async (route: Route, payload: unknown, status = 200) => {
  await route.fulfill({
    status,
    contentType: 'application/json',
    body: JSON.stringify(payload)
  })
}

const clearStorage = async (page: Page) => {
  await page.goto('about:blank')
  await page.evaluate(() => {
    window.localStorage.clear()
    window.sessionStorage.clear()
  })
}

test.describe('Meeting panel', () => {
  test.beforeEach(async ({ page }) => {
    await clearStorage(page)
  })

  test('creates a meeting session and shows transcript details', async ({ page }) => {
    const sessions: MeetingSessionSummary[] = []
    const details: Record<string, MeetingSessionDetail> = {}

    await page.route('**/health*', async (route) => {
      await fulfillJson(route, {
        status: 'ok',
        voiceFeatureEnabled: false,
        services: [
          { name: 'meeting', status: 'ok' },
          { name: 'mcp0', status: 'ok' }
        ]
      })
    })

    await page.route('**/mcp/providers*', async (route) => {
      await fulfillJson(route, [])
    })

    await page.route(`${API_BASE}/meeting/sessions`, async (route) => {
      const method = route.request().method()
      if (method === 'POST') {
        const body = JSON.parse(route.request().postData() || '{}') as {
          sessionId?: string
          title?: string
        }
        const sessionId = body.sessionId || `meeting-${Date.now()}`
        const title = body.title || 'Untitled meeting'
        const now = new Date().toISOString()
        const summary: MeetingSessionSummary = {
          session_id: sessionId,
          title,
          participants: [],
          entry_count: 1,
          created_at: now,
          updated_at: now
        }
        const detail: MeetingSessionDetail = {
          ...summary,
          language_hint: 'en-US',
          tags: ['automation'],
          summary: null,
          entries: [
            {
              text: 'Discussed browser automation harness.',
              speaker: 'Alice',
              created_at: now,
              metadata: { source: 'browser_stt' }
            }
          ]
        }
        sessions.unshift(summary)
        details[sessionId] = detail
        await fulfillJson(route, detail)
        return
      }

      await fulfillJson(route, { sessions })
    })

    await page.route('**/meeting/sessions/*', async (route) => {
      const url = new URL(route.request().url())
      const method = route.request().method()
      const path = url.pathname
      const summarizeMatch = path.match(/\/meeting\/sessions\/(.+)\/summarize$/)
      if (summarizeMatch && method === 'POST') {
        const sessionId = summarizeMatch[1]
        const summaryText = 'Summary generated by automation harness.'
        const detail = details[sessionId]
        if (detail) {
          detail.summary = summaryText
          detail.updated_at = new Date().toISOString()
        }
        await fulfillJson(route, {
          session_id: sessionId,
          summary: summaryText,
          entries_considered: detail?.entries.length || 0
        })
        return
      }

      const detailMatch = path.match(/\/meeting\/sessions\/([^/]+)$/)
      if (detailMatch && method === 'GET') {
        const sessionId = detailMatch[1]
        const detail = details[sessionId]
        if (!detail) {
          await fulfillJson(route, { error: 'not_found' }, 404)
          return
        }
        await fulfillJson(route, detail)
        return
      }

      await route.fallback()
    })

    await page.goto('/')
    await Promise.all([
      page.waitForResponse((res) => res.url().includes('/health')),
      page.waitForResponse((res) => res.url().includes('/mcp/providers'))
    ])

    await page.getByRole('button', { name: 'Meeting' }).click()
    await expect(page.getByTestId('meeting-panel')).toBeVisible()
    await expect(page.getByText('No sessions yet.')).toBeVisible()

    const title = 'Playwright sync-up'
    await page.getByTestId('meeting-title-input').fill(title)

    await Promise.all([
      page.waitForResponse(
        (res) =>
          res.url().startsWith(`${API_BASE}/meeting/sessions`) && res.request().method() === 'POST'
      ),
      page.getByTestId('meeting-start-button').click()
    ])

    const sessionCard = page.getByTestId('meeting-session-card').first()
    await expect(sessionCard).toContainText(title)

    await Promise.all([
      page.waitForResponse((res) =>
        res.url().startsWith(`${API_BASE}/meeting/sessions/`) && res.request().method() === 'GET'
      ),
      sessionCard.click()
    ])

    await expect(page.getByTestId('meeting-detail')).toBeVisible()
    await expect(page.getByTestId('meeting-entry').first()).toContainText('Discussed browser automation harness.')

    await Promise.all([
      page.waitForResponse((res) => res.url().includes('/summarize')),
      page.getByTestId('meeting-summary-button').click()
    ])

    await expect(page.getByTestId('meeting-summary-card')).toContainText('Summary generated by automation harness.')
  })
})
